project:
  type: website

website:
  title: "English Catalogue of Books"
  navbar:
    left:
      - href: publishers.qmd
        text: Top Publishers 
      - href: authors.qmd
        text: Top Authors
      - href: our_data.qmd
        text: Our Data
      - href: entrycapture.qmd
        text: Captured Entries

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

metadata-files:
  - _params.yml



