project:
  type: website
  resources:
    - data/*.json
    - data/all_titles_by_year.csv

website:
  title: "English Catalogue of Books"
  navbar:
    left:
      - text: About
        menu:
          - text: About Our Project
            href: about_project.qmd
          - text: About Our Sources
            href: sources.qmd
          - text: Collaborators
            href: about_team.qmd
      - href: our_data.qmd
        text: Our Data
      - text: Visualizations
        menu:
          - text: Top Publishers by Year
            href: publishers.qmd
          - text: Top Authors by Year
            href: authors.qmd
          - text: Independent Visualizations
            href: independent_viz.qmd
      - text: Data Explorer 
        menu:
          - text: N-Gram Viewer
            href: https://english-catalogue-ngram.streamlit.app/
            target: _blank
          - text: Interactive Map
            href: map.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
  
metadata-files:
  - _params.yml



